// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Title       string  `json:"Title"`
	Content     string  `json:"Content"`
	Author      *string `json:"Author,omitempty"`
	Hero        *string `json:"Hero,omitempty"`
	PublishedAt *string `json:"Published_At,omitempty"`
	UpdatedAt   *string `json:"Updated_At,omitempty"`
}

type NewVpc struct {
	CidrBlock *string `json:"CidrBlock,omitempty"`
}

type Post struct {
	ID          int    `json:"id"`
	Title       string `json:"Title"`
	Content     string `json:"Content"`
	Author      string `json:"Author"`
	Hero        string `json:"Hero"`
	PublishedAt string `json:"Published_At"`
	UpdatedAt   string `json:"Updated_At"`
}

type Vpc struct {
	ID                          int     `json:"id"`
	AmazonProvidedIpv6CidrBlock *bool   `json:"AmazonProvidedIpv6CidrBlock,omitempty"`
	CidrBlock                   *string `json:"CidrBlock,omitempty"`
	EnableDNSHostNames          *bool   `json:"EnableDnsHostNames,omitempty"`
	EnableDNSSupport            *bool   `json:"EnableDnsSupport,omitempty"`
	InstanceTenancy             *string `json:"InstanceTenancy,omitempty"`
	Ipv6CidrBlock               *string `json:"Ipv6CidrBlock,omitempty"`
	Ipv6Pool                    *string `json:"Ipv6Pool,omitempty"`
	Region                      *string `json:"Region,omitempty"`
}
